<a href="https://colab.research.google.com/github/ShwetaBaranwal/HandsonML/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [30]:
X = iris["data"][:, 3:]
y = (iris['target']==2).astype('int').reshape(150,1) # converting to binary class

In [4]:
def sigmoid(x):
  return 1/ (1+ np.exp(x))

In [5]:
p = sigmoid(np.dot(X, np.array([1])))
p.shape

(150,)

In [6]:
linear_predictions = np.dot(X, np.random.rand(1))
predictions = sigmoid(linear_predictions)

In [7]:
predictions.shape

(150,)

In [8]:
def accuracy(y_pred, y_true):
  return np.mean(y_pred == y_true)

In [31]:
X.shape

(150, 1)

In [61]:
class LogisticRegression:
  def __init__(self, lr=0.01, n_iter=200):
    self.lr = lr
    self.n_iter = n_iter
    self.intercept_ = None
    self.coef_ = None
    self.classes = None

  def fit(self, X, y):
    m, n = X.shape
    X_b = np.c_[np.ones((m,1)), X]
    self.classes = np.unique(y)
    theta_gd =  np.array([-2,5]).reshape(2,1) #np.random.rand(n+1,1)

    for i in range(self.n_iter):
      linear_predictions = np.dot(X_b, theta_gd)
      predictions = sigmoid(linear_predictions)
      grad = 2/m * X_b.T.dot(predictions-y)
      theta_gd = theta_gd - self.lr*grad

    self.intercept_ = theta_gd[0]
    self.coef_ = theta_gd[1:]
    return self.intercept_, self.coef_

  def predict(self, X, thresh=0.5):
    linear_pred = np.dot(X, self.coef_)+self.intercept_
    pred =  sigmoid(linear_pred)
    return np.where(pred<thresh, 0, 1)

  def predict_proba(self, X):
    linear_pred = np.dot(X, self.coef_)+self.intercept_
    pred =  sigmoid(linear_pred)
    return pred


In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=42)

In [66]:
log_reg = LogisticRegression(0.1, 50)
log_reg.fit(X_train, y_train)

(array([0.58397725]), array([[11.93524435]]))

In [67]:
y_train_pred = log_reg.predict(X_train)
y_test_pred = log_reg.predict(X_test)
accuracy(y_train_pred, y_train), accuracy(y_test_pred, y_test)

(0.6444444444444445, 0.7)

using package

In [50]:
from sklearn.linear_model import LogisticRegression

In [52]:
log_reg_package = LogisticRegression(random_state=42)
y_train = y_train.reshape(90)
log_reg_package.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [53]:
y_pred_package = log_reg_package.predict(X_test)

In [54]:
accuracy(y_pred_package, y_test)

0.5666666666666667

In [55]:
log_reg_package.intercept_, log_reg_package.coef_

(array([-5.65632002]), array([[3.44957244]]))

In [56]:
y_pred_package

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])